spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.126.125:3306/myself?serveTimezone=GMT%2B8
    username: rootroot
    password: root
#打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#baidu





#  global-config:
#    db-config:
#      table-prefix: xxx  设置表格统一前缀


# #多环境开发
# #配置不同的环境
# spring:
#   profiles:
#     active: test
# #终端运行 选择环境 java -jar xxxx.jar --spring.profiles.active=test
# # java -jar xxx.jar --serve.port = 20 改变端口
# #分隔符
# ---
# #开发
# spring:
#   profiles: dev
# server:
#   port: 9090

# ---
# #生产
# server:
#   port: 8080
# spring:
#   profiles: hh

# ---
# #测试
# server:
#   port: 9091
# spring:
#   profiles: test
